# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'GitHubClient' do
pod 'AFNetworking', '~> 2.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~>3.8'
pod 'JSONModel'
end

target 'GitHubClientTests' do

end

target 'GitHubClientUITests' do

end

